Import("env")  # must be first — SCons injects 'env' via this call
import os

try:
    example_src = env.GetProjectOption("custom_example_src")
except Exception:
    print("link_example.py: 'custom_example_src' not set, skipping.")
    Exit(0)

project_dir = env.subst("$PROJECT_DIR")
src_dir     = os.path.join(project_dir, "src")
example_abs = os.path.normpath(os.path.join(project_dir, example_src))

if not os.path.isdir(example_abs):
    print(f"link_example.py: Example folder not found: {example_abs}")
    Exit(1)

# Resolve entry file (Arduino .ino preferred, ESP-IDF main.cpp fallback)
entry_path = None
ino_files = [f for f in os.listdir(example_abs) if f.endswith(".ino")]
if ino_files:
    entry_path = os.path.join(example_abs, ino_files[0])
else:
    main_cpp = os.path.join(example_abs, "main.cpp")
    if os.path.isfile(main_cpp):
        entry_path = main_cpp

if entry_path is None:
    print(f"link_example.py: No entry file found in {example_abs} (expected .ino or main.cpp)")
    Exit(1)

# Write a main.cpp shim into src/ that #includes the .ino directly.
# SCons scans src/ before running pre-scripts, but main.cpp already
# exists from a previous build — on first build, we need the shim
# present before SCons starts. For that reason we also write it here
# (it will be present for all subsequent builds immediately).
os.makedirs(src_dir, exist_ok=True)
shim_path = os.path.join(src_dir, "main.cpp")
backup_path = os.path.join(src_dir, ".main.cpp.et-backup")

# Use forward slashes and escape backslashes for the #include path
include_path = entry_path.replace("\\", "/")

generated_marker = "Auto-generated by link_example.py"

shim = f"""\
// Auto-generated by link_example.py -- do not edit.
// Includes the selected example entry file for the active environment.
#include "{include_path}"
"""

original_exists = os.path.exists(shim_path)
if original_exists:
    with open(shim_path, "r", encoding="utf-8", errors="ignore") as f:
        existing_content = f.read()

    if generated_marker not in existing_content:
        with open(backup_path, "w", encoding="utf-8") as f:
            f.write(existing_content)


def _cleanup_shim():
    if os.path.exists(backup_path):
        with open(backup_path, "r", encoding="utf-8") as f:
            original = f.read()
        with open(shim_path, "w", encoding="utf-8") as f:
            f.write(original)
        os.remove(backup_path)
        print(f"link_example.py: restored original {shim_path}")
        return

    if os.path.exists(shim_path):
        with open(shim_path, "r", encoding="utf-8", errors="ignore") as f:
            current = f.read()
        if generated_marker in current:
            os.remove(shim_path)
            print(f"link_example.py: removed generated {shim_path}")


def _cleanup_shim_post_action(source, target, env):
    _cleanup_shim()


env.AddPostAction("$BUILD_DIR/${PROGNAME}.elf", _cleanup_shim_post_action)
env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", _cleanup_shim_post_action)

with open(shim_path, "w") as f:
    f.write(shim)

print(f"link_example.py: wrote shim {shim_path} -> includes {entry_path}")