; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
lib_deps = 
	hideakitai/ArxContainer@^0.7.0
    throwtheswitch/Unity@^2.6.1
test_ignore = examples/*
test_build_src = yes

[env:native]
platform = native
build_flags = 
	-Itest/Mocks/arduino
    -D unitTesting
test_ignore = 
    esp32/*

[env:native_coverage]
platform = native
build_flags =
    -Itest/Mocks/arduino
    -D unitTesting
    -lgcov
    --coverage
    -fprofile-abs-path
test_ignore =
    esp32/*

[env:esp32s3_arduino]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

build_flags =
    -D SDMMC_PIN_CLK=14
    -D SDMMC_PIN_CMD=15
    -D SDMMC_PIN_D0=2
    -D SDMMC_PIN_D1=4
    -D SDMMC_PIN_D2=12
    -D SDMMC_PIN_D3=13
    -D SDMMC_BUS_WIDTH=4
    -DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
    

test_speed = 115200
; test_port = COM9
; upload_port = COM4
monitor_speed = 115200
test_ignore = 
    *native*
test_filter = 
    *
    arduino/*
    esp32/*


[env:esp32s3_espressif]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
test_speed = 115200
monitor_speed = 115200
test_ignore = 
    *native*
    arduino/*
test_filter = 
    *
    esp32/*
build_flags =
    -D SDMMC_PIN_CLK=14
    -D SDMMC_PIN_CMD=15
    -D SDMMC_PIN_D0=2
    -D SDMMC_PIN_D1=4
    -D SDMMC_PIN_D2=12
    -D SDMMC_PIN_D3=13
    -D SDMMC_BUS_WIDTH=4
    -DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
; test_port = COM9
; upload_port = COM4
